payroll/urls.py
from django.conf.urls import patterns, include, url, handler404
from django.contrib import admin
from django.conf import settings
admin.autodiscover()

urlpatterns = patterns('',
    url(r'', include('payroll.apps.registration.auth_urls')),
    url(r'^$', 'payroll.apps.calculator.views.home', name='home'),
    url(r'^employee/save/?$', 'payroll.apps.calculator.views.save_employee', name='save_ee'),
    url(r'^calculator/ytd/?$', 'payroll.apps.calculator.views.get_year_to_date', name='ytd'),
    url(r'^calculator/save/?$', 'payroll.apps.calculator.views.save_paycheck_data', name='save'),
    url(r'^calculator/autocomplete-employee/$', 'payroll.apps.calculator.views.autocomplete_employee', name='autocomplete'),
    url(r'^calculator/not-found/?$', 'payroll.apps.calculator.views.handler404', name='not-found'),
    url(r'^calculator/?$', 'payroll.apps.calculator.views.calculator', name='calculator'),
    url(r'^last-calculation/?$', 'payroll.apps.calculator.views.get_last_calculation', name='last_calculation'),
    url(r'^last-calculation/(?P<employee>.*)/?$', 'payroll.apps.calculator.views.get_last_calculation', name='last_calculation_filter'),
    url(r'^successfully-logged-out/?$', 'payroll.apps.calculator.views.successfully_logged_out', name='successfully_logged_out'),
    url(r'^help/$', 'payroll.apps.calculator.views.help', name='help'),
    url(r'^history/?$', 'payroll.apps.calculator.views.history', name='history'),
    url(r'^not-supported/?$', 'payroll.apps.calculator.views.not_supported', name='not_supported'),
    url(r'^recommend/?$', 'payroll.apps.calculator.views.recommend', name='recommend'),
    url(r'^contact/?$', 'payroll.apps.calculator.views.contact', name='contact'),
    url(r'^proxy/', 'payroll.apps.calculator.views.proxy', name='proxy'),
    url(r'^proxyLS/', 'payroll.apps.calculator.views.proxyls', name='proxyls'),
	url(r'^accounts/', include('payroll.apps.registration.backends.default.urls')),
    url(r'^admin/', include(admin.site.urls)),
)

handler404 = 'payroll.apps.calculator.views.handler404'

if settings.DEBUG:
    urlpatterns += patterns('django.contrib.staticfiles.views',
        url(r'^static/(?P<path>.*)$', 'serve'),
    )

payroll/apps/calculator/models.py
from django.db import models
from django.conf import settings
from django.core.mail import send_mail
from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser
)
from enums import *
from datetime import datetime

class PayrollUserManager(BaseUserManager):
    def create_user(self, email, password=None):

        if not email:
            raise ValueError('Users must have an email address')
 
        user = self.model(
            email=PayrollUserManager.normalize_email(email),
        )
 
        user.set_password(password)
        user.save(using=self._db)
        return user
 
    def create_superuser(self, email, password):
        user = self.create_user(
        	email,
            password=password,
        )
        user.is_active = True
        user.is_admin = True
        user.save(using=self._db)
        return user
 
class PayrollUser(AbstractBaseUser):
    objects = PayrollUserManager()
    email = models.EmailField(max_length=254, unique=True)
    accountant_email = models.EmailField(max_length=254, blank=True, null=True)

    USERNAME_FIELD = 'email'
    
    is_active = models.BooleanField(default=False)
    is_admin = models.BooleanField(default=False)

    def get_full_name(self):
        return self.email
 
    def get_short_name(self):
        return self.email
 
    def __unicode__(self):
        return self.email
 
    def has_perm(self, perm, obj=None):
        # Handle whether the user has a specific permission?"
        return True
 
    def has_module_perms(self, app_label):
        # Handle whether the user has permissions to view the app `app_label`?"
        return True

    def email_user(self, subject, message, from_email=None):
        """
        Sends an email to this User.
        """
        send_mail(subject, message, from_email, [self.email])
 
    @property
    def is_staff(self):
        # Handle whether the user is a member of staff?"
        return self.is_admin

class Employee(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    name = models.CharField(max_length=60)
    created = models.DateField(auto_now_add=True, default=datetime.now())
    deleted = models.BooleanField(default=False)

    def __unicode__(self):
        return self.name

class EntryData(models.Model):
    employee = models.ForeignKey(Employee)
    created = models.DateField(auto_now_add=True, default=datetime.now())
    state = models.CharField(max_length=2, choices = INTUIT_STATES)
    
    #This is a fix value for current year.     
    gross_ytd = models.FloatField(default=0, null=True, blank=True)
    # Pay Information
    pay_date = models.DateField(null=True, blank=True)
    pay_period = models.SmallIntegerField(choices = INTUIT_PAY_PERIOD,null=True, blank=True)
    pay_type = models.SmallIntegerField(choices = INTUIT_PAY_TYPE,null=True, blank=True)
    hours_worked = models.IntegerField(default=0, null=True, blank=True)
    pay_rate_hs = models.FloatField(default=0, null=True, blank=True)
    # Pay Additional
    overtime_worked = models.FloatField(default=0, null=True, blank=True)
    salary = models.FloatField(default=0, null=True, blank=True)
    bonus = models.FloatField(default=0, null=True, blank=True)
    commission = models.FloatField(default=0, null=True, blank=True)
    # Federal Witholdings
    filing_status = models.SmallIntegerField(choices = INTUIT_FILING_STATUS,null=True, blank=True)
    exemptions = models.IntegerField(default=0, null=True, blank=True)
    additional_withholding = models.FloatField(default=0, null=True, blank=True)
    
    def __unicode__(self):
        return self.employee.name

    class Meta():
        verbose_name = "Entry Data"
        verbose_name_plural = "Entry Data"

class EntryStateData(models.Model):
    entry = models.ForeignKey(EntryData)
    name = models.CharField(max_length=50)
    value = models.CharField(max_length=30)

    def __unicode__(self):
        return self.name

class ResultData(models.Model):
    entry = models.ForeignKey(EntryData)
    created = models.DateField(auto_now_add=True, default=datetime.now())
    # Result
    state = models.CharField(max_length=2, choices = INTUIT_STATES)
    pay_date = models.DateField(null=True, blank=True)
    pay_rate_hs = models.FloatField(default=0, null=True, blank=True)
    net_pay = models.FloatField(default=0, null=True, blank=True)
    hours_total = models.FloatField(default=0, null=True, blank=True)
    hours_worked = models.FloatField(default=0, null=True, blank=True)
    gross_pay = models.FloatField(default=0, null=True, blank=True)
    # Other fields
    salary = models.FloatField(default=0, null=True, blank=True)
    bonus = models.FloatField(default=0, null=True, blank=True)
    commission = models.FloatField(default=0, null=True, blank=True)
    is_salary = models.BooleanField(default=False)
    ot_hours_worked = models.FloatField(default=0, null=True, blank=True)
    ot_pay_rate_hs = models.FloatField(default=0, null=True, blank=True)
    ot_total = models.FloatField(default=0, null=True, blank=True)
    
    # YEAR-TO-DATE
    gross_pay_ytd = models.FloatField(default=0, null=True, blank=True)
    net_pay_ytd = models.FloatField(default=0, null=True, blank=True)
    # Other fields
    salary_ytd = models.FloatField(default=0, null=True, blank=True)
    bonus_ytd = models.FloatField(default=0, null=True, blank=True)
    commission_ytd = models.FloatField(default=0, null=True, blank=True)

    def __unicode__(self):
        return self.entry.employee.name

    class Meta():
        verbose_name = "Result Data"
        verbose_name_plural = "Result Data"


class ResultTaxData(models.Model):
    result = models.ForeignKey(ResultData, blank=True, null=True)

    name = models.CharField(max_length=50)
    amount = models.FloatField(default=0)

    # YEAR-TO-DATE
    amount_ytd = models.FloatField(default=0)

    def __unicode__(self):
        return self.name

class ReportData(ResultData):

    class Meta:
        proxy = True    
        verbose_name = "Paycheck Calculation History"
        verbose_name_plural = "Paycheck Calculation History"

payroll/apps/calculator/forms.py
try:
    from django.contrib.auth import get_user_model
except ImportError: # django < 1.5
    from django.contrib.auth.models import User
else:
    User = get_user_model()
from django import forms
from django.utils.translation import ugettext_lazy as _

attrs_dict = {'class': 'required'}

# from django import forms
# from django.forms.fields import email_re

# class MultipleEmailsField(forms.Field):
#     def clean(self, value):
#         """
#         Check that the field contains one or more comma-separated emails
#         and normalizes the data to a list of the email strings.
#         """
#         if not value:
#             raise forms.ValidationError('Enter at least one e-mail address.')
#         emails = value.split(',')
#         for email in emails:
#             if not email_re.match(email):
#                 raise forms.ValidationError('%s is not a valid e-mail address.' % email)
#         return emails

class ContactForm(forms.Form):
    email = forms.EmailField(widget=forms.TextInput(attrs=dict(attrs_dict,
                                                               maxlength=75)),
                             label=_("Your Email"))
    message = forms.CharField(widget=forms.Textarea(attrs={'rows': 5,'class':'required'}),
                                label=_("Message"))

class ResetPasswordForm(forms.Form):
    email = forms.EmailField(widget=forms.TextInput(attrs=dict(attrs_dict,
                                                               maxlength=75)),
                             label=_("Your Email"))

class AccountantForm(forms.Form):
    clients = forms.CharField(widget=forms.TextInput(attrs=dict(attrs_dict,
                                                               maxlength=75)),
                             label=u"Client's Emails",
                             help_text=u"Comma separated")

    email = forms.EmailField(widget=forms.TextInput(attrs=dict(attrs_dict,
                                                               maxlength=75)),
                             label=_("Your Email"))
    message = forms.CharField(widget=forms.Textarea(attrs={'rows': 5,'class':'required'}),
                                label=_("Message"))

templates/base.html
<!doctype html>
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<title>{% block title %}Intuit Easy Paycheck{% endblock %}</title>
	<meta name="description" content="">
	<meta name="viewport" content="width=device-width">
	<meta name="apple-mobile-web-app-capable" content="yes" />
	<link href="{{STATIC_URL}}css/intuit.min.css" rel="stylesheet" type="text/css" media="screen"/>
	<link href="{{STATIC_URL}}css/intuit-responsive.min.css" rel="stylesheet" type="text/css" media="screen"/>
	{% block extra_style %}{% endblock %}

	<script src="{{STATIC_URL}}js/vendor/modernizr-2.6.2.min.js"></script>
<!--[if lte IE 8]><script src="{{STATIC_URL}}js/intuit/ie-upgrade.js"></script><script>window.onload=function(){e("{{STATIC_URL}}img/")}</script><![endif]-->
<!-- GA Tracking -->
<script type="text/javascript">
	var _gaq = _gaq || [];
	_gaq.push(['_setAccount', '{{ga_uuid}}']);
	_gaq.push(['_setDomainName', '{{ga_property}}']);
	_gaq.push(['_trackPageview']);
  	_gaq.push(['_setCustomVar', 1, 'IUID', '{{request.session.iuid}}', 2]);
	(function() {
    	var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    	ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    	var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  	})();
</script>
</head>
<body>
	<div class="navbar navbar-fixed-top">
		<div class="navbar-inner">
			<h1><a class="brand" href="/"  data-intuit="check-saved">Intuit Easy Paycheck</a></h1>
			<ul class="nav">
			  <li {% ifequal nav 'calculator'%}class="active"{%endifequal%}><a id="nav-calculator" href="{% url 'home' %}"  data-intuit="check-saved">Calculate Checks</a></li>
			  <li {% ifequal nav 'history'%}class="active"{%endifequal%}><a id="nav-history" href="{% url 'history' %}" data-intuit="check-saved">View History</a></li>
			</ul>
			<ul class="login nav pull-right">
			{% if user.is_authenticated %}
			<li class="dropdown">
				<a class="dropdown-toggle" data-toggle="dropdown" href="#">{{ user.email }} <b class="caret"></b></a>
				<ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
					<li><a href="{% url 'auth_password_change' %}" role="button" data-intuit="check-saved">Change Password</a></li>
					<li><a href="{% url 'auth_logout' %}" role="button" data-intuit="check-saved">Logout</a></li>
				</ul>
			</li>
<!--			  <li class="navbar-text">Welcome <strong>{{ user.email }}</strong></li> -->
			  <li><a href="#ContactModal" role="button" data-toggle="modal">Contact Us</a></li>
			{% else %}
			  <li><a href="#LoginModal" role="button" data-toggle="modal">Sign In</a></li>
			  <li><a href="#RegistrationModal" role="button" data-toggle="modal">Sign Up</a></li>
			  <li><a href="#ContactModal" role="button" data-toggle="modal">Contact Us</a></li>
			{% endif %}
			</ul>
		</div>
	</div>

	<div id="container" data-toggle="popover">
	{% block content %}{% endblock %}
	</div>

{% if not user.is_authenticated %}
{% include "modal/login.html" %}
{% include "modal/accountant.html" %}
{% endif %}
{% include "modal/registration.html" %}
{% include "modal/contact_us.html" %}

<script src="{{STATIC_URL}}js/vendor/jquery-1.8.3.min.js"></script>
<script src="{{STATIC_URL}}js/intuit.min.js"></script>
<!-- I need integrate this libraries into intuit.min -->
<script src="{{STATIC_URL}}js/intuit/analytics.js"></script>
<script src="{{STATIC_URL}}js/intuit/contact.js"></script>
<script src="{{STATIC_URL}}js/intuit/registration.js"></script>
<script src="{{STATIC_URL}}js/intuit/invoice.js"></script>

{% if not user.is_authenticated %}
<script src="{{STATIC_URL}}js/intuit/login.js"></script>
<script src="{{STATIC_URL}}js/intuit/accountant.js"></script>
<script>
	window.authenticated = false;
	window.username = "Anonymous";
</script>
{% else %}
<script>
	window.authenticated = true;
	window.username = "{{ user.email }}";
</script>
{% endif %}

{% block extra_script %}{% endblock %}
</body>
</html>

templates/base_account.html
<!doctype html>
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<title>Intuit Easy Paycheck</title>
	<meta name="description" content="">
	<meta name="viewport" content="width=device-width">
	<meta name="apple-mobile-web-app-capable" content="yes" />
	<link href="{{STATIC_URL}}css/intuit.min.css" rel="stylesheet" type="text/css" media="screen"/>
	<link href="{{STATIC_URL}}css/intuit-responsive.min.css" rel="stylesheet" type="text/css" media="screen"/>
	{% block extra_style %}{% endblock %}
	
	<script src="{{STATIC_URL}}js/vendor/modernizr-2.6.2.min.js"></script>
<!--[if lte IE 8]><script src="{{STATIC_URL}}js/intuit/ie-upgrade.js"></script><script>window.onload=function(){e("{{STATIC_URL}}img/")}</script><![endif]-->
</head>
<body>
	<div class="navbar navbar-fixed-top">
		<div class="navbar-inner">
			<h1><a class="brand" href="/">Intuit Easy Paycheck</a></h1>
			<ul class="nav">
			  <li {% ifequal nav 'calculator'%}class="active"{%endifequal%}><a id="nav-calculator" href="{% url 'home' %}">Calculate Checks</a></li>
			  <li {% ifequal nav 'history'%}class="active"{%endifequal%}><a id="nav-history" href="{% url 'history' %}">View History</a></li>
			</ul>
		</div>
	</div>

	<div id="container" data-toggle="popover">
	{% block content %}{% endblock %}
	</div>
	

{% if not user.is_authenticated %}
{% include "modal/login.html" %}   
{% include "modal/accountant.html" %}   
{% endif %}
{% include "modal/registration.html" %}   
{% include "modal/contact_us.html" %}   

<!-- GA Tracking -->
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-41115413-1', 'ikenta.com');
  ga('send', 'pageview');
</script>

<script src="{{STATIC_URL}}js/vendor/jquery-1.8.3.min.js"></script>
<script src="{{STATIC_URL}}js/intuit.min.js"></script>
<!-- I need integrate this libraries into intuit.min -->
<script src="{{STATIC_URL}}js/intuit/analytics.js"></script>
<script src="{{STATIC_URL}}js/intuit/contact.js"></script>
<script src="{{STATIC_URL}}js/intuit/registration.js"></script>
<script src="{{STATIC_URL}}js/intuit/invoice.js"></script>

{% if not user.is_authenticated %}
<script src="{{STATIC_URL}}js/intuit/login.js"></script>
<script src="{{STATIC_URL}}js/intuit/accountant.js"></script>
<script>
	window.authenticated = false;
	window.username = "Anonymous";
</script>
{% else %}
<script>
	window.authenticated = true;
	window.username = "{{ user.email }}";
</script>
{% endif %}

{% block extra_script %}{% endblock %}

</body>
</html>

templates/calculator.html
{% extends 'base.html' %}

{% block content %}
<div id="slider">
    <section id="calculator-input">
    	<div class="section-inner">
{% if user.is_authenticated %}
    	<h1>Woo! Let's calculate some more checks!</h1>
{% else %}
    	<h1>Welcome! Let’s calculate your first paycheck!</h1>
{% endif %}
    	{% include 'calculator/calculator_form.html' %}
    	</div>
    </section>

    <section id="calculator-result">
    	<div class="section-inner">
    		<a id="btn-calculate" href="#" class="btn btn-primary btn-large">Calculate this check!</a>
    	</div>
    </section>

    <section id="calculator-share">
    	<div class="section-inner">
    		<h1>Here is your new paycheck for ...!</h1>
    		<p>Want to make a change? <a id="btn-recalculate" href="#">Re-calculate this check</a></p>
    	</div>
    </section>
	<div id="accountant-share">
		<p>Are you an accountant? <a href="#AccountantModal" role="button" data-toggle="modal">Invite your client!</a></p>
	</div>
</div>
{% endblock %}

{% block extra_script %}

{% include 'calculator/calculator_result.html'  %}
{% include 'calculator/calculator_share.html'  %}
{% include "modal/save_paycheck.html" %}

{% load compress %}

<script src="{{STATIC_URL}}js/vendor/hogan-2.0.0.min.js"></script>
<script src="{{STATIC_URL}}js/vendor/jquery.history.js"></script>

{% compress js %}
<script src="{{STATIC_URL}}js/vendor/jquery.autocomplete.js"></script>
<script src="{{STATIC_URL}}js/intuit/plugins.js"></script>
<script src="{{STATIC_URL}}js/intuit/validations.js"></script>
<script src="{{STATIC_URL}}js/intuit/calculator.js"></script>
{% endcompress %}

{% compress js inline %}
<script type="text/javascript">
$(document).ready(function() {

    var aux = $('#pay_date').datepicker({
    	  format: 'mm/dd/yyyy'
        }).on('changeDate', function(ev) {
        	if (ev.viewMode === 'days')
         		$(this).datepicker('hide');
        });
	$(".form_calendar").click(function() {
		$("#pay_date").datepicker('show');
	});

	/*
	 * If not logged user, show popover message
	 */
	if (!window.authenticated) {

		$('#container').popover({
			animation: true,
			html: true,
			title: "Add your first employee!",
			content:  "Or, <a href='#LoginModal' role='button' data-toggle='modal'>Sign In</a> to use your saved employees.",
			trigger: 'manual'
		});
		$('#container').popover('show');
		var pos = $('#employee').offset();
		$('.popover').css({ top: (pos.top-20)+'px', left: (pos.left+220)+'px', maxWidth: 'none', width: '320px' });
		$('#employee').bind('blur', function() {
			$('#container').popover('hide');
			$('#container').popover('destroy')
		});
	}

	/*
	 * Check if user want to leave the calculator without save
	 */
	 $('body').on('click', 'a[data-intuit="check-saved"]', function(e){
	 	var that = this;
	 	if (intuit.calculator.need_save()) {
	 		e.preventDefault();
	 		var r = intuit.calculator.result();
	 		$('#SavePaycheckModal .save-employee').html(r.employee);
	 		$('#SavePaycheckModal .save-pay-date').html(r.pay_date);
	 		$('#SavePaycheckModal .save-net-pay').html($('<strong/>').html('$ ' + r.net_pay));

		 	$('#SavePaycheckModal').modal();
		 	$('#SavePaycheckModal').on('hidden', function(){
		 		$('#btn-exit').off('click');
		 	});

		 	$('#btn-exit').on('click',function(e) {
			 	e.preventDefault();
			 	document.location.href=that.href;
			 	return false;
			 });

		 	return false;
	 	}
	 	return true;
	 });
});
</script>
{% endcompress %}
{% endblock %}

templates/history.html
{% extends 'base.html' %}
{% load currency %}

{% block content %}

<div class="section-inner history">

{% if user.is_authenticated %}
	<h1>Here are all of the paychecks you have calculated and saved.</h1>
	<p class="delete-message">If you would like to delete a  check, please <a href="#ContactModal" role="button" data-toggle="modal">Contact Us</a> and let us know which one.</p>
<table class="table table-bordered table-hover">
	<thead>
		<tr>
			<th width="20%">Pay Date <span class="caret"></span></th>
			<th width="40%">Employee</th>
			<th width="25%" class="amount">Net Pay Amount</th>
			<th width="15%" class="detail">Details</th>
		</tr>
	</thead>
	<tbody>
{% for inv in invoices %}
		<tr>
			<td class="id hidden">{{inv.id}}</td>
			<td>{{inv.pay_date|date:"m/d/Y"}}</td>
			<td>{{inv.entry.employee.name}}</td>
			<td class="amount"><strong>$ {{inv.net_pay | currency}}</strong></td>
			<td class="detail"><a href="#"><img src="{{STATIC_URL}}img/detail_icon.png" /></a></td>
		</tr>
{% endfor %}
	</tbody>
</table>

{% else %}
	<h1>You haven’t calculated any paychecks yet!</h1>
	<p class="info-1"><a href="{% url 'calculator' %}">Calculate your first paycheck</a> to get started!</p>  
	<p class="info-2">Or, <a href="#LoginModal" role="button" data-toggle="modal">Sign In</a> to view your saved history.</p>
{% endif %}
</div>

{% include 'calculator/calculator_result.html'  %}
{% include 'modal/invoice.html' %}
{% endblock %}

{% block extra_script %}
{% if user.is_authenticated %}	

<script src="{{STATIC_URL}}js/vendor/hogan-2.0.0.min.js"></script>

<script type="text/javascript">
$(document).ready(function() {
	var invoices = [
{% for inv in invoices %}
				{	
					id: {{inv.id}},
					employee: "{{inv.entry.employee.name}}",
					pay_date: '{{inv.pay_date|date:"m/d/Y"}}',
					net_pay: "{{inv.net_pay|currency}}",
					pay_rate_hs: "{{inv.pay_rate_hs|currency}}",
				    hours_total: {{inv.hours_total}},
				    hours_worked: {{inv.hours_worked}},
				    gross_pay: "{{inv.gross_pay|currency}}",
				    salary: {% if inv.salary %}"{{inv.salary|currency}}"{% else %}0{%endif%},
				    bonus: {% if inv.bonus %}"{{inv.bonus|currency}}"{% else %}0{%endif%},
				    commission: {% if inv.commission %}"{{inv.commission|currency}}"{% else %}0{%endif%},
				    ot_hours_worked: {% if inv.ot_hours_worked %}"{{inv.ot_hours_worked|currency}}"{% else %}0{%endif%},
				    ot_pay_rate_hs: {% if inv.ot_pay_rate_hs %}"{{inv.ot_pay_rate_hs|currency}}"{% else %}0{%endif%},
				    ot_total: {% if inv.ot_total %}"{{inv.ot_total|currency}}"{% else %}0{%endif%},
				    
				    taxes: [
						{% for tax in inv.resulttaxdata_set.all %}
				    	{
				    		name: "{{tax.name}}",
				    		amount: "{{tax.amount|currency}}"
				    	},
				    	{% endfor %}
				    ]
				},
{% endfor %} 	
		]	
	$('tr a').click(function() {

		var tr = $(this).closest('tr'),
			sel_id = $('.id', tr).html()
		for (var i = 0; i < invoices.length; i++) {
		    if (invoices[i].id == sel_id) {
				tpl = Hogan.compile(document.querySelector('#calculator-result-tpl').innerHTML);
				$('#InvoiceModal .modal-body').html(tpl.render(invoices[i]));		
				$('#InvoiceModal').modal();		    
		    }
 		}
	});	
	_gaq.push(['_trackEvent', 'User', 'History']);
	_gaq.push(['_trackEvent', window.username, 'History']);
})
</script>
{% else %}
<script type="text/javascript">
$(document).ready(function() {
	_gaq.push(['_trackEvent', 'Anonymous', 'History']);	
})
</script>

{% endif %}
{% endblock %}